# error warning use my color 
theme="dark_plus"

[editor]
# Show currently open buffers, only when more than one exists.=bufferline = "multiple"
#bufferline = "multiple"

# Highlight all lines with a cursor
cursorline = true



# Show a ruler at column 120 + 1 ruler    eq terminal 125x44  = 120 cols x 42 for src 
rulers = [120]

# Force the theme to show colors
true-color = true

mouse = true

auto-format =false

auto-save = true

middle-click-paste= false

scroll-lines = 1


[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers"]

[editor.gutters.line-numbers]
min-width = 1


[editor.indent-guides]
character = "│"
render = true

[editor.file-picker]
hidden = false
parents = false
git-ignore = false



[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"



[editor.whitespace.render]
space = "all"
newline = "all"
tab = "all"

[editor.whitespace.characters]
space = " "
newline = "⏎"
tab = "→"


[editor.soft-wrap]
max-wrap =0	    # espace before ruler
enable = true



[editor.statusline]
left = ["mode","spinner"]
center = ["file-name","file-modification-indicator"]
#right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
right = [ "diagnostics", "position", "total-line-numbers"]
separator = "│"

mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

#LSP snippets are a way for language servers to provide more complex completions for an editor
#display-inlay-hints = false


[editor.search]
smart-case = true
wrap-around = true


[keys.normal]
C-n = ["file_picker_in_current_directory"] # Maps Ctrl-n split new vertical get feil dir
C-s = ":w"
C-c = ["yank_main_selection_to_clipboard"]
C-v = ["replace_selections_with_clipboard"]


# create a new minor mode bound to `+`
[keys.normal."+"]
m = ":sh gnome-terminal --title='Menu-General...' --hide-menubar -- ../MenuDEV.sh && exit"
g = ":sh gnome-terminal --title='Compile-Gencurs' --hide-menubar -- ../Compile_Zig.sh 'Gencurs' && exit"
h = ":sh gnome-terminal --title='Compile-Gensrc.' --hide-menubar -- ../Compile_Zig.sh 'Gensrc'  && exit"
x = ":sh gnome-terminal --title='Compile-mdlsrc.' --hide-menubar -- ../Compile_Zig.sh 'mdlSrc'  && exit"
w = ":sh gnome-terminal --title='Enr.Memoire(66)' --hide-menubar -- $HOME/.Terminal/copyZig.sh && exit"
c = ":sh $HOME/.Terminal/console.sh  && exit"
