
# error warning use my color 
theme="mytheme"

[editor]
# Show currently open buffers, only when more than one exists.=bufferline = "multiple"
bufferline = "multiple"

# Highlight all lines with a cursor
cursorline = true

# Show a ruler at column 120 + 1 ruler
rulers = [121]
# Force the theme to show colors
true-color = true

mouse = true

auto-format =false

middle-click-paste= true

scroll-lines = 1



[editor.whitespace.render]
space = "all"
tab ="all"
[editor.whitespace.characters]
space = "·"
tab = "→"

[editor.indent-guides]
character = "│"
render = true

[editor.file-picker]
hidden = false
parents = false
git-ignore = false



[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"




[editor.soft-wrap]
max-wrap =0		# espace before ruler
enable = true





[editor.statusline]
left = ["mode","spinner"]
center = ["file-name","file-modification-indicator"]
#right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
right = [ "diagnostics", "position", "total-line-numbers",  "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"



[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

#LSP snippets are a way for language servers to provide more complex completions for an editor
display-inlay-hints = true

[editor.search]
smart-case = true
wrap-around = true

[keys.normal]
# Use system clipboard  copy/paste
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"

# historique and last work source
A-q = ":sh xfce4-terminal --hide-menubar --hide-scrollbar --hide-toolbar    --geometry='80x26'  --title='MENUSRC' -x /home/soleil/.Terminal/copyZig.sh  && exit"

# select line up
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]


[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
