# error warning use my color 
theme="dark_plus"

[editor]
# Show currently open buffers, only when more than one exists.=bufferline = "multiple"
bufferline = "never"

popup-border = "all"

# Highlight all lines with a cursor
cursorline = true

cursorcolumn = true

# Show a ruler at column 120 + 1 ruler    eq terminal 125x44  = 120 cols x 42 for src 
rulers = [120]

# Force the theme to show colors
#true-color = false

color-modes = true

mouse = true

auto-format =false

middle-click-paste= false

scroll-lines = 1



continue-comments = false

end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers"]

[editor.gutters.line-numbers]
min-width = 1


[editor.indent-guides]
character = "│"
render = true

[editor.file-picker]
hidden = false
parents = false
git-ignore = false



[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"



[editor.whitespace.render]
space = "all"
newline = "all"
tab = "all"




[editor.whitespace.characters]
space = " "
newline = "⏎"
tab = "→"


[editor.soft-wrap]
max-wrap =0	    # espace before ruler
enable = true


[editor.statusline]
left = ["mode","spinner"]
center = ["file-name","file-modification-indicator"]
#right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
right = [ "diagnostics", "position", "total-line-numbers"]
separator = "│"

mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true


[editor.search]
smart-case = true
wrap-around = true


[keys.normal]
C-a = [":vnew",":open /home/soleil/Zsnipset"]
C-s = [":write"]
C-c = ["yank_main_selection_to_clipboard"]
C-v = ["replace_selections_with_clipboard"]
C-l = [":clear-register"]
C-d = ["delete_selection"]
C-u = ["undo"]
C-r = ["redo"]
C-t = ["toggle_line_comments","move_line_down"]
C-h = ["hover"]
A-i = ["insert_at_line_start"]
A-e = ["insert_at_line_end"]
A-m = ["match_brackets"]
A-d = ["goto_next_diag"]
A-D = ["goto_first_diag"]
A-f = ["file_picker_in_current_directory"]
A-F = ["file_picker"]
A-n = ["vsplit_new"]
A-v = ["vsplit"]
A-q = ["search"]
A-g = ["goto_last_line"]


[keys.insert]
C-s = ["normal_mode",":write"]
C-c = ["yank_main_selection_to_clipboard"]
C-v = ["replace_selections_with_clipboard"]
C-l = [":clear-register"]
C-d = ["delete_selection"]
C-u = ["undo"]
C-r = ["redo"]
C-t = ["toggle_line_comments","move_line_down"]
C-h = ["hover"]
A-m = ["match_brackets"]
A-d = ["goto_next_diag"]
A-D = ["goto_first_diag"]


#create a new minor mode bound to `+`
[keys.normal."+"]
w = ":sh gnome-terminal --title='Enr.Memoire(66)' --hide-menubar -- $HOME/.Terminal/copyZig.sh && exit"
c = ":sh $HOME/.Terminal/console.sh  && exit"

