[language-server.zls]
command = "zls-lsp"
args = ["--stdio"]

[language-server.zls.config]
lint = true
inlayHint.enable = true


[[language]]
name = "zig"
scope = "source.zig"
injection-regex = "zig"
file-types = ["zig"]
comment-token = "//"
indent = { tab-width = 4, unit = " " }
language-server = { command = "zls-lsp", args = ["--stdio"], environment = { "ENV1" = "value1", "ENV2" = "value2" } }
#formatter = { command = "zig-formatter" , args = ["--stdin"]}

